/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
repositories {
    maven {url = uri("https://maven.aliyun.com/repository/public/") }
    mavenLocal()
    mavenCentral()
}
plugins{
    id("java")
    id("org.springframework.boot") version "2.2.0.RELEASE"
    id("io.spring.dependency-management") version "1.0.8.RELEASE"
}

dependencies{
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("mysql:mysql-connector-java:8.0.18")
    compile("org.mybatis:mybatis:3.5.3")
    compile("org.apache.httpcomponents:httpclient:4.5.10")
    compile("org.freemarker:freemarker:2.3.29")
    compile("org.apache.commons:commons-collections4:4.1")
}

tasks {
    bootJar {
        mainClassName = "hello.Application"
    }
}